version: '3.9'
services:
  db_test:
    image: postgis/postgis:15-3.3
    container_name: db_test
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
    ports:
      - ${DB_PORT_TEST}:${DB_PORT_TEST}
