version: '3.9'
services:
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - MODULE_NAME=${MODULE_NAME}
      - PRE_START_PATH=${PRE_START_PATH}
      - PORT=${APP_PORT}
    expose:
      - ${APP_PORT}
    restart: always

  nginx:
    image: nginx:1.25.2
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  db-data:
